[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "nodejs_18"]

[phases.install]
cmds = [
  "cd server && pip3 install --upgrade pip",
  "cd server && pip3 install -r requirements.txt",
  "npm install",
]

[phases.build]
cmds = [
  "npm run build",
]

[start]
cmd = "cd server && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 120"

